name: ftd
description: dill transform
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"


dev_dependencies:
  kernel: any
  front_end: any
  package_config: any
  args: any

dependency_overrides:
  kernel:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: pkg/kernel
  vm:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: pkg/vm
  frontend_server:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: pkg/frontend_server
  front_end:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: pkg/front_end
  dev_compiler:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: pkg/dev_compiler
  package_config:
    git:
      url: git@gitee.com:idouziAndroid/alsdk.git
      ref: stable/v1.22.3
      path: third_party/pkg_tested/package_config
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

